Command line formatting support and other small changes
LoomDev/Loom pull request #16
Opened 2020-12-31 16:28 UTC by TheKodeToad

Adds support for chat formatting in the command line.
It also adds some small improvements:

- `mvn package` -> `./loom jar` (uses `mvn clean package` meaning that old classes and javadoc doesn't hang around)
- sendActionbar -> sendActionBar (action bar is 2 words)
- Fix spelling in javadoc.
- Adds more links to javadoc.
- Changes `Loom task logger - <task number>` to `Task logger - <task number>`

2020-12-31 18:27 UTC, thatgoofydev requested changes
This doesn't seem to support custom RGB colors (see screenshot). Is it possible to add support for these as well?

![image](https://user-images.githubusercontent.com/10576071/103421697-007c6380-4b9e-11eb-9162-51e6a8989f8b.png)

2020-12-31 18:27 UTC, thatgoofydev commented on server/src/main/java/org/loomdev/loom/util/ChatUtil.java
> +public class ChatUtil {
I don't like naming classes a Util.

A more descriptive name for what this class actually does could be ChatComponentToStringFormatter or ChatComponentFormatter if you would like to shorten it.

(I would also rename the `toString` method to `format` in case of the first one)

2020-12-31 18:27 UTC, thatgoofydev commented on server/src/main/java/org/loomdev/loom/util/ChatUtil.java
> +public class ChatUtil {
Since this is a static class I would also prefer if it is marked as final and contained a private constructor to prevent it from being instantiated.

In other static classes in the util package we also include a 
`throw new UnsupportedOperationException("You should not be attempting to instantiate this class.");`
statement in the constructor, this could prevent make it extra clear to future developers that the class is always meant to be static.

2020-12-31 18:27 UTC, thatgoofydev commented on server/src/main/java/org/loomdev/loom/util/ChatUtil.java
> +    public static String toString(Component component) {
If a method never returns null, we have the convention of marking it with an `@NotNull` annotation (from org.jetbrains.annotations).

2020-12-31 18:27 UTC, thatgoofydev commented on server/src/main/java/org/loomdev/loom/util/ChatUtil.java
> +    }
These methods are only used internally so should be private. The names of these methods also do not reflect what they do. Try to give them a more descriptive name.

2020-12-31 18:27 UTC, thatgoofydev commented on server/src/main/java/org/loomdev/loom/util/ChatUtil.java
> +    public static List<Component> components(Component component) {
This methods is unnecessary, this one line of code can perfectly be executed in the `toString` method. For readability put the results in a variable first and use the variable in the loop.

2020-12-31 18:27 UTC, thatgoofydev commented on README.md
> +To build a complete Loom JAR, you will need to have [Maven](https://maven.apache.org/) installed. Once installed, run the setup commands above, followed by `./loom jar`. The final JAR will be inside
The maven information might better be moved to the `./loom setup` step, setup already makes use of maven.

Also while you are already here would you mind changing `The final JAR will be inside the `target/` folder.` to `The final JAR will be inside the root directory.` 😅 (otherwise I'll do it later)

2021-01-02 11:12 UTC, TheKodeToad commented
Until https://github.com/Minecrell/TerminalConsoleAppender/pull/17 is merged, RGB will not be supported.

2021-01-02 12:17 UTC, thatgoofydev approved these changes
The changes look good!

2021-01-02 12:33 UTC, thatgoofydev commented
> Also, another irrelevant comment: if this project used [Gradle](https://gradle.org/) rather than Maven it would allow the project to be build without having Maven installed, because Gradle has a wrapper that automatically downloads itself. It would also allow all of the Bash scripts to be moved to Gradle build scripts.

Somewhere in August 2020 I did actually change the project to use Gradle in a separate branch to see if it would add any additional improvements. I was glad to see that it actually made a somewhat big impact on the build speed. Unfortunately, there was one problem that I could not solve, being that the hot reloading Intelij became buged. So we decided to stick to maven for the time being as we make heavy use of the hot reloading.

I am not an advanced Maven/Gradle user, so there might be a solution to this problem that I just did not find yet.
If we can find a solution for this problem, then we would happily switch to Gradle 🥳

2021-01-02 12:34 UTC, merged