More Javadoc
LoomDev/Loom pull request #8
Opened 2020-12-21 16:23 UTC by TheKodeToad

Lots more Javadoc.

2020-12-21 18:43 UTC, thatgoofydev commented
First of, thank you for the contribution. We really appreciate it!

Some small notes on it though:

1. We want to try to make the Javadoc very user friendly, so more English than some sort of  pseudo programming language. So for example, instead of writing "Get if the version is a snapshot" write "Gets whether the version is a snapshot". (Also note the 'Gets', it describes what the method does. 'The method GETS whether the version is a snapshot')

2. Prevent redundant information like "(if the format is YEAR-w-WEEK-LETTER)" ([ApiVersion](https://github.com/LoomDev/Loom/pull/8/files#diff-b043fae7c8e57bc8ab930564125bad138318b30525b2d26abe1f30e043428badR63)) it doesn't add any extra meaning to the method. (This also might become outdated if Mojang changes their naming schema for snapshots.)

3. Prevent "useless" docs. For example "Represents a version of the API." is kind of useless on a class named "ApiVersion". Same for the documentation on LATEST, LATEST_SNAPSHOT, etc. these speak for themselves.

Lastly, I want to thank you again, feel free to apply some of these changes.

PS If you disagree with some of these notes, please feel free to explain your view on this.
PS PS I do know that are documentation isn't the best right now, so we probably missed some of these notes ourselves 😅 

(final PS)
PS PS PS about Vignette: any numbers on speed improvements? (Just if you know, I'll definitely look into it)

2020-12-22 09:16 UTC, TheKodeToad commented
I agree that "Gets" should be used instead of "Get", I just used "Get" because the original code used it.

2020-12-22 09:50 UTC, TheKodeToad commented
Actually, it turns out that Vignette does not support ProGuard despite it being based on Lorenz which supports ProGuard.

Something that I know for sure works (and is even faster), though is a combination of https://github.com/FabricMC/Enigma and https://github.com/FabricMC/tiny-remapper.

Enigma is good at converting mappings, but not so good at applying them, and Tiny Remapper only supports *.tiny mapping files, so you first run Enigma:
`java -jar enigma.jar convert-mappings proguard server.txt tinyv2:obfuscated:deobfuscated server.tiny`
and then run:
`java -jar tiny-remapper.jar server.jar server-deobf.jar server.tiny obfuscated deobfuscated`.

This isn't ideal, though, as it requires 2 programs.

Here are the downloads:
Enigma: https://maven.fabricmc.net/cuchaz/enigma-cli/0.21.6%2Bbuild.229/enigma-cli-0.21.6%2Bbuild.229-all.jar
Tiny: https://maven.fabricmc.net/net/fabricmc/tiny-remapper/0.3.1.72/tiny-remapper-0.3.1.72-fat.jar

Tiny Remapper only took around about 10 seconds to complete, while Reconstruct took over 2 minutes.

2020-12-22 10:37 UTC, TheKodeToad commented
I have used Git before, but never done a pull request before so it might be broken.

2020-12-22 11:34 UTC, TheKodeToad commented
Flattened commits.

2020-12-22 21:11 UTC, thatgoofydev requested changes
A lot of the time its the same stuff over and over, but its a good start.
I did not add a comment to every singe occurrence of a thing I commented on previously, but I tried to do it at least once per file.

Also a small note for any future PR's try to make them a little smaller, it is way more pleasant for the person doing the review.

If you fix the stuff I mentioned  (and make sure the pipeline doesn't fail) I'll merge it in 😄 

I'll attach a picture of the pipeline, because I don't know for sure if you can see it. (I think so, but I'll add it anyway)
![image](https://user-images.githubusercontent.com/10576071/102933475-94fe0c00-44a2-11eb-969a-af7542bcf923.png)

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/village/VillagerProfession.java
> + * Represents the profession of a villager.
Why remove the link? I think it adds extra context to the interface.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/ApiVersion.java
> +     * @return Whether the version is newer that the other version.
Spelling error "that" instead of "than".

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/ApiVersion.java
> +     * @return Whether the version is newer that the other version.
For the `@return` statement something like `@return True when the version is newer than the other version.` would be more descriptive and gives more insight into what the method exactly returns.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/ApiVersion.java
> +     * @return Whether the version is newer that the other version.
There are a lot of places this is the case, so I am not going to put this comment everywhere.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/Loom.java
> +     *
This is an internal method and should never be used by a plugin, only by implementations of the API. A nice addition here would be a note for this. example. "Note: This method is for internal use only, and should never be used by a plugin".

The other comments can stay 😉

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/block/BlockPointer.java
> +     */
This comment doesn't add any extra meaning or explanation to the method.
It is a Javadoc comment just to have a Javadoc comment...

Same with basically every comment on the methods of this interface.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/block/BlockPointer.java
> + * Represents a block in a world.
BlockPointer is an interesting type in the API they are a stateless reference to a block in a world. All the return values of the getters can change based on the time you call the getter. The only value that will always be the same is the Location. 

Maybe something explaining this concept might be interesting.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/block/BlockState.java
> +     * Gets the block state's block type.
"Get the block type of the state" would read more easily.

But it also does not add extra meaning or explanation to the method

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/block/BlockType.java
> +     * @param id The id of the block to get.
Good catch! 👍

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/block/enums/Instrument.java
> +     * Gets an instrument from its name.
*by its name

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/block/enums/Instrument.java
> +     * Gets the sound event for the instrument.
Doesn't add extra meaning or explanation. 

Something more you could describe here is that its the SoundEvent that the instrument makes when the noteblock is activated

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/block/enums/Note.java
> +     */
No extra meaning or explanation

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/block/enums/Note.java
> +     */
Same for the rest of the methods

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/block/enums/Note.java
> +     */
Here you could explain the index more, describe what exactly it is.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/block/enums/Note.java
> +     */
Same index/uses comment as above

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/block/enums/Octave.java
> +     */
No extra meaning or explanation

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/bossbar/BossBar.java
> + * Boss bars are usually used to show a boss' health, but is commonly used to show a countdown or display text at the top of a player's screen.
This is part of the BossBar API, people can do all sorts of things with it. Its not a utility for showing countdowns, etc. this comment might give people the idea that it supports countdowns, etc. without having to provide extra logic.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/command/CommandContext.java
> + * Represents a command context containing the source, alias and arguments.
Something like mentioned below might be easier to understand for people trying to use the API.

"
Describes the context a command was execute in.
Contains information like the {@link CommandSource} that executed the command, the alias that was used, etc.
"

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/command/CommandManager.java
> + * Represents a command manager.
Does not provide any extra clarity to what it actually does.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/Ageable.java
> +     * @return {@code true} if the entity is a baby, otherwise {@code false}.
Why do you remove {@} tags in some location in Colorable  but add them in other locations?

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/Colorable.java
> +     * @return The dye color of the entity.
See Ageable.java

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/Ageable.java
> +     * @return {@code true} if the entity is a baby, otherwise {@code false}.
Personally I think they can add extra context or easy linking. They also don't hurt anyone by being there, so I don't know why you removed them at other places.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/Entity.java
> +     * Gets the entity's UUID (unique identifier).
"(unique identifier)" is somewhat redundant since the meaning of UUID (Universally unique identifier) already covers it.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/Entity.java
> +     * Gets the entity's bounding box.
Doesn't add anything

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/Entity.java
> +     */
Doesn't add anything

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/Entity.java
> +     */
Doesn't add anything

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/Entity.java
> +     */
Doesn't add anything
Same for isInsideBubbleColumn, isTouchingRainOrWater and isInsideWaterOrBubbleColumn

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/EntityType.java
> +     */
This field is used to denote whether the entity can be summoned with the summon command, as well as spawn from Spawners, etc.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/LivingEntity.java
> + */
Maybe describe what an living entity is.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/Explosive.java
>       */
Yup, I am guilty of writing this useless documentation 😞

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/animal/Cat.java
>       */
Again why remove the links?

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/animal/Fox.java
> +     * @return The {@link Variant} of the fox.
Same as cat

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/animal/Mooshroom.java
>       */
Same as cat

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/animal/Panda.java
>       */
Same as cat

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/animal/Parrot.java
>       */
Same as cat

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/animal/Rabbit.java
>       */
Here the link isn't removed?

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/animal/fish/Pufferfish.java
>       */
You keep it higher up in the file but remove it here?

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/animal/horse/Llama.java
>       */
Same as cat

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/damage/DamageSource.java
>  public enum DamageSource {
This should probably be removed if its not used. If it is used then you are completely right 🤣

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/decoration/Painting.java
>       */
Same as cat

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/bossbar/BossBar.java
> +     */
Maybe mention something about that all future changes to the bossbar are also shown to the player

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/bossbar/BossBar.java
> +     * Removes a player from the boss bar causing it to be invisible to them.
I don't really like the word invisible here 🤷

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/bossbar/BossBar.java
> +         */
Same as above

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/effect/StatusEffect.java
> +     */
"Ambient effects produce translucent particles." might be better than "(produces more particles that are translucent)"

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/effect/StatusEffect.java
> +     */
Also this information might be better put in a separate paragraph (<p></p>)

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/effect/StatusEffect.java
> +         */
same as above

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/npc/Villager.java
> +     */
Doesn't add anything

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/npc/Villager.java
> +     */
same below

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/player/Player.java
> +     * Gets the player's walking/land speed (default: {@code 0.1f}).
I like the addition of the default value 👍

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/player/Player.java
> +     */
Doesn't add anything, same for a lot of the other comment in this interface

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/player/Player.java
>       */
Same as Cat

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/projectile/ShulkerBullet.java
> + * Represents a shulker entity.
Its specifically the bullet that the shulker fires

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/projectile/ShulkerBullet.java
>       */
Consistency, you added "shulker" to the top method but not to the bottom one

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/projectile/SpectralArrow.java
>       */
same as cat

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/entity/vehicle/Boat.java
>       */
Same as cat

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/event/Event.java
> +     */
Doesn't add anything

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/event/Event.java
> +     */
same below

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/event/EventManager.java
> +     */
Maybe document something that and event fired using this method will not return any changes to the event type. Its basically only used for read only events.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/event/EventManager.java
> +     */
same as above

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/event/EventOrder.java
> + */
This isn't necessarily true, since LATEST event can possible be skipped if they use `@Subscribe(ignoreCancelled = true)` meaning that if a subscriber that has an order of EARLIEST cancels the event the LATEST subscriber is not event called.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/item/Enchantment.java
>       */
Same as cat

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/item/Enchantment.java
>       */
same below

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/item/property/ItemProperty.java
>       */
Again same as Cat

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/item/property/ItemProperty.java
>       */
Same below

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/item/property/ItemProperty.java
> +     * @return {@code true} if the {@link ItemProperty van be applied}.
should be `{@code true} if the {@link ItemProperty}  can be applied.` a spelling and format error on my part.

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/item/property/data/DamageData.java
>       */
Same as in Cat (same below)

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/item/property/data/EnchantmentData.java
>       * @return Map of enchantment and level.
Same as in Cat (same below)

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/item/property/data/LoreData.java
>       */
Same as in Cat (same below)

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/item/property/data/NameData.java
>   */
Same as in Cat (same below)

2020-12-22 21:11 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/util/NamespacedKey.java
> +     * @return A loom namespaced key.
Minecraft not loom

2020-12-23 16:49 UTC, thatgoofydev commented on api/src/main/java/org/loomdev/api/Loom.java
> +     * @see Server#getPluginManager()
Very nice!

2020-12-23 17:03 UTC, thatgoofydev commented
The changes look very good!

If you fix the pipeline errors, I can merge it in 😄

2020-12-23 17:03 UTC, thatgoofydev approved these changes

2020-12-23 17:50 UTC, TheKodeToad commented
I've fixed the Javadoc errors. Sorry for making such a big pull request. This is my first pull request on GitHub.

2020-12-24 16:54 UTC, merged